name: QDK build in Github Actions 

# 定义工作流的触发条件：推送到 master 分支或手动触发
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    # 定义环境变量 QPKG_NAME，默认为 'MyQPKG'
    env:
      QPKG_NAME: 'MyQPKG'
      QPKG_VER: '0.1'
      QPKG_AUTHOR: 'Richard Hu'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境为 3.8
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # 克隆 QDK 存储库并安装
    - name: Install QDK
      run: |
        sudo apt-get install -y build-essential wget bsdmainutils curl openssl rsync
        git clone https://github.com/qnap-dev/QDK.git
        cd QDK
        echo "Compiler QPKG encrypt"
        cd src
        sudo make
        cd ../
        echo "Install QDK"
        sudo cp -rf ./shared /usr/share/QDK
        sudo [ -d "/etc/config" ] || sudo mkdir "/etc/config"
        sudo cp ./shared/qdk.conf /etc/config
        sudo sed -e '2d' ./shared/qdk.conf | sudo tee /etc/config/qdk.conf > /dev/null
        sudo sed -i '2iQDK_PATH_P=/usr/share' /etc/config/qdk.conf
        sudo echo "PATH=$PATH:/usr/share/QDK/bin" | sudo tee -a ~/.bashrc > /dev/null
        source ~/.bashrc

    # 配置 QDK 环境并创建 QPKG
    - name: Configure QDK environment
      run: |
        # 获取 QDK 安装路径并切换目录
        cd /usr/share/QDK/bin
        # 使用环境变量 QPKG_NAME 创建 QPKG
        sudo ./qbuild --create-env $QPKG_NAME

    # 编辑 qpkg.cfg 文件中的变量
    - name: Edit qpkg.cfg variables
      run: |
        find / -name MyQPKG -d
        # 前往 QPKG 文件夹
        cd $QPKG_NAME
        cat qpkg.cfg
