name: Install QDK on Ubuntu 22

# 定义工作流的触发条件：推送到 main 分支或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    # 定义环境变量 QPKG_NAME，默认为 'MyQPKG'
    env:
      QPKG_NAME: 'MyQPKG'
      QPKG_VER: '0.1'
      QPKG_AUTHOR: 'Richard Hu'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境为 3.8
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # 克隆 QDK 存储库并安装
    - name: Install QDK
      run: |
        sudo apt-get install -y build-essential wget bsdmainutils curl openssl rsync
        git clone https://github.com/qnap-dev/QDK.git
        cd QDK
        echo "Compiler QPKG encrypt"
        cd src
        make
        cd ../
        echo "Install QDK"
        cp -rf ./shared /usr/share/QDK
        [ -d "/etc/config" ] || mkdir "/etc/config"
        cp ./shared/qdk.conf /etc/config
        sed -e '2d' ./shared/qdk.conf > /etc/config/qdk.conf
        sed -i '2iQDK_PATH_P=/usr/share' /etc/config/qdk.conf
        echo "PATH=$PATH:/usr/share/QDK/bin" >> ~/.bashrc
        source ~/.bashrc

    # 配置 QDK 环境并创建 QPKG
    - name: Configure QDK environment
      run: |
        # 获取 QDK 安装路径并切换目录
        cd `getconf QDK Install_Path -f /etc/config/qpkg.conf`
        # 使用环境变量 QPKG_NAME 创建 QPKG
        qbuild --create-env $QPKG_NAME

    # 编辑 qpkg.cfg 文件中的变量
    - name: Edit qpkg.cfg variables
      run: |
        # 前往 QPKG 文件夹
        cd $QPKG_NAME
        cat qpkg.cfg
